FROM node:alpine

RUN apk update && apk add chromium
RUN apt-get -y install mtr

ARG PORT
ENV PORT=${PORT}
ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}
ARG DEBUG
ENV DEBUG=${DEBUG}
ARG DATABASE
ENV DATABASE=${DATABASE}
ARG DATABASE_LOCAL
ENV DATABASE_LOCAL=${DATABASE_LOCAL}
ARG DATABASE_PASSWORD
ENV DATABASE_PASSWORD=${DATABASE_PASSWORD}

ARG JWT_SECRET
ENV JWT_SECRET=${JWT_SECRET}
ARG JWT_EXPIRE
ENV JWT_EXPIRE=${JWT_EXPIRE}
ARG WEATHER_API_KEY
ENV WEATHER_API_KEY=${WEATHER_API_KEY}

ARG SPACES_ACCESS_KEY
ENV SPACES_ACCESS_KEY=${SPACES_ACCESS_KEY}
ARG SPACES_SECRET_KEY
ENV SPACES_SECRET_KEY=${SPACES_SECRET_KEY}
ARG SPACES_ENPOINT
ENV SPACES_ENPOINT=${SPACES_ENPOINT}

ARG PG_HOST
ENV PG_HOST=${PG_HOST}
ARG PG_DATABASE
ENV PG_DATABASE=${PG_DATABASE}
ARG PG_PORT
ENV PG_PORT=${PG_PORT}
ARG PG_USER
ENV PG_USER=${PG_USER}
ARG PG_PASSWORD
ENV PG_PASSWORD=${PG_PASSWORD}
ARG DB_URL_PG
ENV DB_URL_PG=${DB_URL_PG}

ARG MYSQL_HOST
ENV MYSQL_HOST=${MYSQL_HOST}
ARG MYSQL_DATABASE
ENV MYSQL_DATABASE=${MYSQL_DATABASE}
ARG MYSQL_PORT
ENV MYSQL_PORT=${MYSQL_PORT}
ARG MYSQL_USER
ENV MYSQL_USER=${MYSQL_USER}
ARG MYSQL_PASSWORD
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}
ARG TZ
ENV TZ=${TZ}

ARG PG_HOST_POOL
ENV PG_HOST_POOL=${PG_HOST_POOL}
ARG PG_DATABASE_POOL
ENV PG_DATABASE_POOL=${PG_DATABASE_POOL}
ARG PG_PORT_POOL
ENV PG_PORT_POOL=${PG_PORT_POOL}
ARG PG_USER_POOL
ENV PG_USER_POOL=${PG_USER_POOL}
ARG PG_PASSWORD_POOL
ENV PG_PASSWORD_POOL=${PG_PASSWORD_POOL}

ARG OPEN_AI
ENV OPEN_AI=${OPEN_AI}
ARG FILE_PATH
ENV FILE_PATH=${FILE_PATH}


ARG REDIS_HOST
ENV REDIS_HOST=${REDIS_HOST}
ARG REDIS_PORT
ENV REDIS_PORT=${REDIS_PORT}
ARG REDIS_PASSWORD
ENV REDIS_PASSWORD=${REDIS_PASSWORD}
ARG REDIS_URL
ENV REDIS_URL=${REDIS_URL}

WORKDIR "/app"
COPY ./package.json ./

EXPOSE 8000
RUN npm install

COPY ./ ./

CMD [ "npm", "run", "server" ]
