alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DEPLOYMENT_LIVE
databases:
  - cluster_name: app-db01
    engine: MONGODB
    name: app-db01
    production: true
    version: "4"
  - cluster_name: db-postgresql-blr1-new
    db_name: defaultdb
    db_user: doadmin
    engine: PG
    name: db-postgresql-blr1-new
    production: true
    version: "14"
envs:
  - key: NODE_ENV
    scope: RUN_AND_BUILD_TIME
    value: production
  - key: DEBUG
    scope: RUN_AND_BUILD_TIME
    value: "0"
  - key: WEATHER_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: "ascdsacwdf"
  - key: NPM_CONFIG_PRODUCTION
    scope: RUN_AND_BUILD_TIME
    value: "false"
  - key: TZ
    scope: RUN_AND_BUILD_TIME
    value: America/New_York
features:
  - buildpack-stack=ubuntu-22
ingress:
  rules:
    - component:
        name: nodeproject
      match:
        path:
          prefix: /nodeproject
    - match:
        path:
          prefix: /search
      redirect:
        authority: google.com
        redirect_code: 302
        uri: /
    - component:
        name: mainapp
      match:
        path:
          prefix: /
name: seal-app
region: sfo
services:
  - environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: techswarn/NodeProject
    http_port: 8080
    instance_count: 1
    instance_size_slug: professional-xs
    log_destinations:
      - name: app
        papertrail:
          endpoint: syslog+tls://logs5.papertrailapp.com:24536
      - datadog:
          api_key: 932be2c22e72e1a4e68cf46f9a0d43e9
          endpoint: https://http-intake.logs.datadoghq.com/v1/input
        name: logdatadog
      - logtail:
          token: rMRRTNXGPYJNr4XgUPL36Vxk
        name: Logtail_nodeapp
    name: nodeproject
    run_command: npm run server
    source_dir: /
  - build_command: npm run build
    environment_slug: node-js
    envs:
      - key: REACT_APP_REVIEWS_1_PHOTO_URL
        scope: RUN_AND_BUILD_TIME
        value: https://nursing.fra1.cdn.digitaloceanspaces.com/008-vidutinio-amziaus-moteris_mokymu-dalyve.jpg
    github:
      branch: main
      deploy_on_push: true
      repo: techswarn/mainapp
    http_port: 8080
    instance_count: 2
    instance_size_slug: professional-xs
    name: mainapp
    run_command: npm start
    source_dir: /
workers:
  - dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: techswarn/docker-cron
    instance_count: 1
    instance_size_slug: professional-xs
    name: dockercron
    source_dir: /
