apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: node-server
  name: node-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: node-server
    spec:
      containers:
        - image: swarntech/nodeproject:latest
          name: nodeproject
          ports:
            - containerPort: 8000
          resources: {}
          env:
            - name: PORT
              value: "8000"
            - name: NODE_ENV
              value: "production"
            - name: DEBUG
              value: "0"
            - name: DATABASE
              value: "mongodb+srv://doadmin:<password>@app-db01-fe45a622.mongo.ondigitalocean.com/story?replicaSet=app-db01&tls=true&authSource=admin"
            - name: DATABASE_LOCAL
              value: "mongodb://localhost:27017/natours"
            - name: JWT_EXPIRE
              value: "90"
            - name: SPACES_ENPOINT
              value: "fra1.digitaloceanspaces.com"
            - name: PG_HOST
              value: "db-postgresql-do-user-11648032-0.b.db.ondigitalocean.com"
            - name: PG_DATABASE
              value: "store"
            - name: PG_PORT
              value: "25060"
            - name: PG_USER
              value: "admin"
            - name: MYSQL_HOST
              value: "db-mysql-blr-do-user-11648032-0.b.db.ondigitalocean.com"
            - name: MYSQL_DATABASE
              value: "brad-laravel"
            - name: MYSQL_PORT
              value: "25060"
            - name: MYSQL_USER
              value: "swarn"
            - name: PG_HOST_POOL
              value: "db-postgresql-blr1-new-do-user-11648032-0.b.db.ondigitalocean.com"
            - name: PG_DATABASE_POOL
              value: "pool_1"
            - name: PG_PORT_POOL
              value: "25061"
            - name: PG_USER_POOL
              value: "doadmin"
            - name: FILE_PATH
              value: "./scripts/profile.jpg"
            - name: REDIS_HOST
              value: "redis-10897.c212.ap-south-1-1.ec2.cloud.redislabs.com"
            - name: REDIS_PORT
              value: "10897"
          envFrom:
            - secretRef:
                name: node-server-secret
